INSERT INTO songs (title, artist, year, genre, length) VALUES ('Bohemian Rhapsody', 'Queen', 1975, 'Rock', 354);
INSERT INTO songs (title, artist, year, genre, length) VALUES ('Thriller', 'Michael Jackson', 1982, 'Pop', 358);
INSERT INTO songs (title, artist, year, genre, length) VALUES ('Billie Jean', 'Michael Jackson', 1983, 'Pop', 294);
INSERT INTO songs (title, artist, year, genre, length) VALUES ('Livin\' On A Prayer', 'Bon Jovi', 1986, 'Rock', 254);
INSERT INTO songs (title, artist, year, genre, length) VALUES ('Like a Rolling Stone', 'Bob Dylan', 1965, 'Rock', 369);
INSERT INTO songs (title, artist, year, genre, length) VALUES ('Stairway to Heaven', 'Led Zeppelin', 1971, 'Rock', 480);
INSERT INTO songs (title, artist, year, genre, length) VALUES ('Smells Like Teen Spirit', 'Nirvana', 1991, 'Grunge', 301);
INSERT INTO songs (title, artist, year, genre, length) VALUES ('Hallelujah', 'Jeff Buckley', 1994, 'Rock', 307);
INSERT INTO songs (title, artist, year, genre, length) VALUES ('Lose Yourself', 'Eminem', 2002, 'Hip hop', 337);
INSERT INTO songs (title, artist, year, genre, length) VALUES ('Hotel California', 'Eagles', 1976, 'Rock', 391);
